function draw_obstacle(obstacles)
%DRAW_OBSTACLE Summary of this function goes here
%   Detailed explanation goes here

obstacleNames = fieldnames(obstacles) ;

for n = 1:numel(fieldnames(obstacles))
        ellipse(obstacles.(obstacleNames{n}).position(1),...
            obstacles.(obstacleNames{n}).position(2),...
            obstacles.(obstacleNames{n}).radius,...
            obstacles.(obstacleNames{n}).radius*0.5,...
            atan2(obstacles.(obstacleNames{n}).velocity(2),obstacles.(obstacleNames{n}).velocity(1)),...
            'r') ;

    
%         viscircles(obstacles.(obstacleNames{n}).position(1:2)', ...
%             obstacles.(obstacleNames{n}).radius, ...
%             'Color', 'r', 'LineWidth', 1) ;
        
end

